// Uploads the illustration that ships inside the welcome note.
//
// A note cannot reference a bundled file: markdown carries `bpad-img:ID`, and
// an ID only exists once the bytes have been sealed with the account's data key
// and stored (see images.ts). So the asset Vite bundled is fetched back as
// bytes and uploaded like any picture the user would paste — which is also what
// makes it a working demonstration that images work.
//
// The file is generated by `scripts/generate-welcome-image.py` and is already a
// 1400 px WebP, so it needs no processImage() pass.
import welcomeImageUrl from './assets/welcome-encryption.webp'
import { uploadImage } from './images'

// Best-effort by design: registration must not hinge on this. Returns null on
// any failure, and the caller writes the note without the picture.
export async function uploadWelcomeImage(): Promise<string | null> {
  try {
    const res = await fetch(welcomeImageUrl)
    if (!res.ok) return null
    return await uploadImage(await res.blob())
  } catch {
    return null
  }
}
